name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/install

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/install

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Typecheck
        run: pnpm run typecheck
